### ISSUE TITLE
Messages are still too long

### ISSUE THREAD

**Issue by pynchmeister** [jupediaz/chatgpt-prompt-splitter#1]
Can't seme to get this to work properly via the deployed instance. Tried using GPT-3.5 and 4 but both still say the message submitted was too long.

**Comment by stevenirby** [comment]
Interesting, it is working for me. Did you try changing the custom length?

**Comment by retracd** [comment]
Can back this up, was working for me at the length of 15,000.

**Comment by pynchmeister** [comment]
Will try again and get back to you...

**Comment by jupediaz** [comment]
You can always specify a shorter limit for the chunks. The default value is 15,000 because it worked for me all the time, but I'm indeed using ChatGPT-Plus, and there may be some differences. But if you need, you can specify, let's say, 10,000 characters. Thanks for your interest!
