### ISSUE TITLE
Incorrect Chunk Calculation

### ISSUE THREAD

**Issue by maaac5** [jupediaz/chatgpt-prompt-splitter#4]
Great script, really appreciate your work!

**Issue Description:**

The "Split into" feature in the demo at https://chatgpt-prompt-splitter.jjdiaz.dev is incorrectly calculating the number of chunks for large inputs. When pasting text with approximately 10,000 characters, the application suggests splitting the text into 11 parts instead of the expected number.

**Steps to Reproduce:**

Visit https://chatgpt-prompt-splitter.jjdiaz.dev
Copy and paste text with around 10,000 characters into the "Enter the long prompt to be splitted" textarea.
Observe the suggested number of parts in the "Split into" feature.

**Temporary Fix:**

Select "Max chars length for each splitted part", switch to the "Custom" option, and then switch back to the default option.
Add an empty space into the "Enter the long prompt to be splitted" textarea.

**Screenshots:**

![wXZPwx8lnK](https://user-images.githubusercontent.com/59025292/237034220-ad51b2db-6f13-42ef-b882-3362c07855d6.jpg)

**Comment by jupediaz** [comment]
This was happening only on the first load by a silly bug on the code, all the times later were working fine.

Anyway, now it's fixed.

Thanks!
