### ISSUE TITLE
Vercel deployment success, but website shows 500 error

### ISSUE THREAD

**Issue by darth-pika-hu** [jupediaz/chatgpt-prompt-splitter#5]
![image](https://github.com/jupediaz/chatgpt-prompt-splitter/assets/103236915/65520703-9a64-4fd2-b20e-3b052bf28a4a)

**Comment by jupediaz** [comment]
Not really sure what happened here, but I guess the best way is checking your Vercel deployment log.

This deployment works on Vercel as it's the way I'm deploying. A pair of days ago I deployed a bug fix and it deployed normally.

**Comment by jupediaz** [comment]
I think this issue is not really related with this repository, but with another fork created that could have different setup on Github or Vercel, so I think I can close this issue.

**Comment by spencerthayer** [comment]
Hey @jupediaz it looks like this is a persistent bug.
